import {
  User,
  FPOOrganization,
  MandiMaster,
  CropCatalogItem,
  Transporter,
  PlatformSettings,
  RolePermissions,
} from "./types";

export const initialUsers: User[] = [
  {
    id: "F1",
    name: "Ramesh Patil",
    role: "farmer",
    phone: "9822100011",
    email: "ramesh.patil@krishisetu.in",
    location: "Baramati Cluster, Pune",
    village: "Malegaon BK",
    taluka: "Baramati",
    district: "Pune",
    state: "Maharashtra",
    pincode: "413115",
    lat: 18.1517,
    lng: 74.5772,
    farmAreaAcres: 4.5,
    farmerType: "Small/Marginal",
    primaryCrops: ["Tomato", "Pomegranate"],
    fpoId: "FPO1",
    upiId: "ramesh.patil@okhdfcbank",
    organization: "Registered Progressive Farmer",
    defaultPassword: "demo_password",
    status: "Active",
    createdAt: "2026-01-15T00:00:00Z",
    updatedAt: "2026-09-07T10:00:00Z",
  },
  {
    id: "F2",
    name: "Suresh Deshmukh",
    role: "farmer",
    phone: "9822100022",
    email: "suresh.deshmukh@krishisetu.in",
    location: "Indapur Cluster, Pune",
    village: "Bhigwan",
    taluka: "Indapur",
    district: "Pune",
    state: "Maharashtra",
    pincode: "413130",
    lat: 18.115,
    lng: 75.025,
    farmAreaAcres: 6.0,
    farmerType: "Medium",
    primaryCrops: ["Onion", "Soybean"],
    fpoId: "FPO1",
    upiId: "suresh.deshmukh@oksbi",
    organization: "Indapur Progressive Farmer Group",
    defaultPassword: "demo_password",
    status: "Active",
    createdAt: "2026-01-20T00:00:00Z",
    updatedAt: "2026-09-07T11:00:00Z",
  },
  {
    id: "F3",
    name: "Gajanan Shinde",
    role: "farmer",
    phone: "9822100044",
    email: "gajanan.shinde@krishisetu.in",
    location: "Parbhani Rural Cluster",
    village: "Karegaon",
    taluka: "Parbhani",
    district: "Parbhani",
    state: "Maharashtra",
    pincode: "431401",
    lat: 19.2608,
    lng: 76.7748,
    farmAreaAcres: 8.0,
    farmerType: "Medium",
    primaryCrops: ["Soybean", "Cotton"],
    fpoId: "FPO3",
    upiId: "gajanan.shinde@barodampay",
    organization: "Parbhani Farmers Group",
    defaultPassword: "demo_password",
    status: "Active",
    createdAt: "2026-02-01T00:00:00Z",
    updatedAt: "2026-09-08T09:00:00Z",
  },
  {
    id: "F4",
    name: "Dattatray Patil",
    role: "farmer",
    phone: "9822100055",
    email: "datta.patil@krishisetu.in",
    location: "Niphad Grape Valley",
    village: "Pimpalgaon",
    taluka: "Niphad",
    district: "Nashik",
    state: "Maharashtra",
    pincode: "422209",
    lat: 20.17,
    lng: 73.98,
    farmAreaAcres: 5.5,
    farmerType: "Small/Marginal",
    primaryCrops: ["Tomato", "Onion", "Grapes"],
    fpoId: "FPO2",
    upiId: "datta.patil@okaxis",
    organization: "Sahyadri Farmer Network",
    defaultPassword: "demo_password",
    status: "Active",
    createdAt: "2026-02-15T00:00:00Z",
    updatedAt: "2026-09-08T10:00:00Z",
  },
  {
    id: "FPO1",
    name: "Saksham FPO",
    role: "fpo",
    phone: "9422088990",
    email: "vikas.kadam@baramatikrushi.org",
    location: "Baramati Krushi Producer Company",
    taluka: "Baramati",
    district: "Pune",
    state: "Maharashtra",
    pincode: "413115",
    lat: 18.1517,
    lng: 74.5772,
    fpoId: "FPO1",
    organization: "Verified FPO Hub (MSAMB Partner)",
    defaultPassword: "demo_password",
    status: "Active",
    createdAt: "2025-11-20T00:00:00Z",
    updatedAt: "2026-09-07T08:00:00Z",
  },
  {
    id: "FPO2",
    name: "Sahyadri Agro FPO Manager",
    role: "fpo",
    phone: "9422088991",
    email: "nitin.sonawane@sahyadrifarms.com",
    location: "Mohadi Mega Packhouse Hub",
    taluka: "Dindori",
    district: "Nashik",
    state: "Maharashtra",
    pincode: "422207",
    lat: 20.006,
    lng: 73.882,
    fpoId: "FPO2",
    organization: "Sahyadri Farmers Producer Co. Ltd.",
    defaultPassword: "demo_password",
    status: "Active",
    createdAt: "2025-08-10T00:00:00Z",
    updatedAt: "2026-09-08T08:30:00Z",
  },
  {
    id: "B1",
    name: "FreshMart Foods Pvt. Ltd.",
    role: "buyer",
    phone: "0202687400",
    email: "procurement@freshmartfoods.in",
    location: "Hadapsar Hub, Pune APMC",
    taluka: "Haveli",
    district: "Pune",
    state: "Maharashtra",
    pincode: "411028",
    lat: 18.502,
    lng: 73.927,
    rating: 4.9,
    paymentReliabilityScore: 98,
    organization: "Certified Institutional Buyer",
    defaultPassword: "demo_password",
    status: "Active",
    createdAt: "2026-03-05T00:00:00Z",
    updatedAt: "2026-09-08T12:00:00Z",
  },
  {
    id: "B2",
    name: "AgroBazaar Wholesale",
    role: "buyer",
    phone: "0222789123",
    email: "orders@agrobazaar.co.in",
    location: "Vashi APMC Market, Navi Mumbai",
    taluka: "Thane",
    district: "Thane",
    state: "Maharashtra",
    pincode: "400703",
    lat: 19.076,
    lng: 72.998,
    rating: 4.7,
    paymentReliabilityScore: 95,
    organization: "Wholesale Terminal Buyer",
    defaultPassword: "demo_password",
    status: "Active",
    createdAt: "2026-02-18T00:00:00Z",
    updatedAt: "2026-09-08T12:00:00Z",
  },
  {
    id: "A1",
    name: "KrishiSetu National Admin",
    role: "admin",
    phone: "0202555123",
    email: "admin@krishisetu.gov.in",
    location: "State Agricultural Operations Center",
    taluka: "Shivajinagar",
    district: "Pune",
    state: "Maharashtra",
    pincode: "411005",
    lat: 18.5204,
    lng: 73.8567,
    organization: "State Portal & Nodal Authority",
    defaultPassword: "demo_password",
    status: "Active",
    createdAt: "2025-10-01T00:00:00Z",
    updatedAt: "2026-09-08T14:00:00Z",
  },
];

export const initialFPOs: FPOOrganization[] = [
  {
    id: "FPO1",
    name: "Baramati Krushi Producer Company Ltd.",
    regNumber: "U01111PN2019PTC184910",
    contactPerson: "Vikas Kadam",
    phone: "9422088990",
    email: "contact@baramatikrushi.org",
    village: "Malegaon BK",
    taluka: "Baramati",
    district: "Pune",
    state: "Maharashtra",
    pincode: "413115",
    lat: 18.1517,
    lng: 74.5772,
    collectionCenters: [
      {
        id: "CC1",
        fpoId: "FPO1",
        name: "Baramati Main Consolidation Hub",
        village: "Malegaon BK",
        taluka: "Baramati",
        district: "Pune",
        state: "Maharashtra",
        pincode: "413115",
        lat: 18.1517,
        lng: 74.5772,
        capacityKg: 25000,
        contactPerson: "Sanjay Shinde",
        phone: "9822345671",
        status: "Active",
      },
      {
        id: "CC2",
        fpoId: "FPO1",
        name: "Indapur Rural Collection Point",
        village: "Bhigwan",
        taluka: "Indapur",
        district: "Pune",
        state: "Maharashtra",
        pincode: "413130",
        lat: 18.115,
        lng: 75.025,
        capacityKg: 15000,
        contactPerson: "Mahesh Jadhav",
        phone: "9822345672",
        status: "Active",
      },
    ],
    supportedCrops: ["Tomato", "Onion", "Pomegranate", "Soybean"],
    serviceFeePaisePerQtl: 150,
    poolMinKg: 500,
    poolMaxKg: 10000,
    defaultPoolClosingDays: 3,
    managerIds: ["FPO1"],
    memberFarmerIds: ["F1", "F2"],
    status: "Active",
    notes: "Nodal primary partner for Pune-Solapur corridor pooling.",
    createdAt: "2025-11-20T00:00:00Z",
  },
  {
    id: "FPO2",
    name: "Sahyadri Farmers Producer Co. Ltd.",
    regNumber: "U01403MH2010PTC201880",
    contactPerson: "Nitin Sonawane",
    phone: "9422088991",
    email: "info@sahyadrifarms.com",
    village: "Mohadi",
    taluka: "Dindori",
    district: "Nashik",
    state: "Maharashtra",
    pincode: "422207",
    lat: 20.006,
    lng: 73.882,
    collectionCenters: [
      {
        id: "CC3",
        fpoId: "FPO2",
        name: "Mohadi Mega Food Park Hub",
        village: "Mohadi",
        taluka: "Dindori",
        district: "Nashik",
        state: "Maharashtra",
        pincode: "422207",
        lat: 20.006,
        lng: 73.882,
        capacityKg: 50000,
        contactPerson: "Pravin More",
        phone: "9822345673",
        status: "Active",
      },
      {
        id: "CC4",
        fpoId: "FPO2",
        name: "Pimpalgaon Baswant Collection Yard",
        village: "Pimpalgaon",
        taluka: "Niphad",
        district: "Nashik",
        state: "Maharashtra",
        pincode: "422209",
        lat: 20.17,
        lng: 73.98,
        capacityKg: 30000,
        contactPerson: "Amol Gaikwad",
        phone: "9822345674",
        status: "Active",
      },
    ],
    supportedCrops: ["Tomato", "Onion", "Grapes", "Pomegranate"],
    serviceFeePaisePerQtl: 180,
    poolMinKg: 1000,
    poolMaxKg: 20000,
    defaultPoolClosingDays: 2,
    managerIds: ["FPO2"],
    memberFarmerIds: ["F4"],
    status: "Active",
    notes: "Largest horticulture FPO in western India with cold chain facilities.",
    createdAt: "2025-08-10T00:00:00Z",
  },
  {
    id: "FPO3",
    name: "Mahavikas Krishi Producer Co. Ltd.",
    regNumber: "U01100MH2021PTC362140",
    contactPerson: "Ashok Rathod",
    phone: "9422088992",
    email: "contact@mahavikaskrishi.in",
    village: "Karegaon",
    taluka: "Parbhani",
    district: "Parbhani",
    state: "Maharashtra",
    pincode: "431401",
    lat: 19.2608,
    lng: 76.7748,
    collectionCenters: [
      {
        id: "CC5",
        fpoId: "FPO3",
        name: "Parbhani Central Yard Hub",
        village: "Karegaon",
        taluka: "Parbhani",
        district: "Parbhani",
        state: "Maharashtra",
        pincode: "431401",
        lat: 19.2608,
        lng: 76.7748,
        capacityKg: 20000,
        contactPerson: "Raju Pawar",
        phone: "9822345675",
        status: "Active",
      },
    ],
    supportedCrops: ["Soybean", "Cotton", "Wheat", "Gram"],
    serviceFeePaisePerQtl: 120,
    poolMinKg: 500,
    poolMaxKg: 15000,
    defaultPoolClosingDays: 4,
    managerIds: [],
    memberFarmerIds: ["F3"],
    status: "Active",
    notes: "Marathwada pulses and oilseed producer aggregation hub.",
    createdAt: "2026-01-05T00:00:00Z",
  },
];

export const initialMandisMaster: MandiMaster[] = [
  // Parbhani
  {
    id: "MANDI-PBN-01",
    mandi: "Parbhani APMC",
    marketCode: "MH-PBN-001",
    district: "Parbhani",
    state: "Maharashtra",
    pincode: "431401",
    lat: 19.2608,
    lng: 76.7748,
    supportedCrops: ["Soybean", "Cotton", "Tur (Arhar)", "Gram", "Wheat", "Tomato"],
    dataSource: "Agmarknet (Govt of India)",
    status: "Active",
    lastSyncAt: "2026-09-08T06:00:00Z",
  },
  {
    id: "MANDI-PBN-02",
    mandi: "Gangakhed APMC",
    marketCode: "MH-PBN-002",
    district: "Parbhani",
    state: "Maharashtra",
    pincode: "431514",
    lat: 18.9567,
    lng: 76.7533,
    supportedCrops: ["Soybean", "Cotton", "Gram"],
    dataSource: "MSAMB",
    status: "Active",
    lastSyncAt: "2026-09-08T06:30:00Z",
  },
  {
    id: "MANDI-PBN-03",
    mandi: "Jintur APMC",
    marketCode: "MH-PBN-003",
    district: "Parbhani",
    state: "Maharashtra",
    pincode: "431509",
    lat: 19.6144,
    lng: 76.6908,
    supportedCrops: ["Soybean", "Cotton", "Wheat"],
    dataSource: "Agmarknet (Govt of India)",
    status: "Active",
    lastSyncAt: "2026-09-08T06:00:00Z",
  },
  {
    id: "MANDI-PBN-04",
    mandi: "Manwath APMC",
    marketCode: "MH-PBN-004",
    district: "Parbhani",
    state: "Maharashtra",
    pincode: "431505",
    lat: 19.3083,
    lng: 76.5022,
    supportedCrops: ["Cotton", "Soybean"],
    dataSource: "Agmarknet (Govt of India)",
    status: "Active",
    lastSyncAt: "2026-09-08T05:30:00Z",
  },
  {
    id: "MANDI-PBN-05",
    mandi: "Selu APMC",
    marketCode: "MH-PBN-005",
    district: "Parbhani",
    state: "Maharashtra",
    pincode: "431503",
    lat: 19.8058,
    lng: 76.4525,
    supportedCrops: ["Cotton", "Soybean", "Gram"],
    dataSource: "MSAMB",
    status: "Active",
    lastSyncAt: "2026-09-08T06:15:00Z",
  },

  // Nashik
  {
    id: "MANDI-NSK-01",
    mandi: "Nashik APMC",
    marketCode: "MH-NSK-001",
    district: "Nashik",
    state: "Maharashtra",
    pincode: "422003",
    lat: 19.9975,
    lng: 73.7898,
    supportedCrops: ["Tomato", "Onion", "Grapes", "Green Chilli", "Pomegranate"],
    dataSource: "Agmarknet (Govt of India)",
    status: "Active",
    lastSyncAt: "2026-09-08T07:00:00Z",
  },
  {
    id: "MANDI-NSK-02",
    mandi: "Pimpalgaon Baswant APMC",
    marketCode: "MH-NSK-002",
    district: "Nashik",
    state: "Maharashtra",
    pincode: "422209",
    lat: 20.17,
    lng: 73.98,
    supportedCrops: ["Tomato", "Onion", "Grapes"],
    dataSource: "e-NAM",
    status: "Active",
    lastSyncAt: "2026-09-08T07:30:00Z",
  },
  {
    id: "MANDI-NSK-03",
    mandi: "Lasalgaon APMC",
    marketCode: "MH-NSK-003",
    district: "Nashik",
    state: "Maharashtra",
    pincode: "422306",
    lat: 20.1464,
    lng: 74.2289,
    supportedCrops: ["Onion", "Tomato", "Soybean"],
    dataSource: "Agmarknet (Govt of India)",
    status: "Active",
    lastSyncAt: "2026-09-08T06:45:00Z",
  },
  {
    id: "MANDI-NSK-04",
    mandi: "Yeola APMC",
    marketCode: "MH-NSK-004",
    district: "Nashik",
    state: "Maharashtra",
    pincode: "423401",
    lat: 20.04,
    lng: 74.48,
    supportedCrops: ["Onion", "Wheat", "Gram"],
    dataSource: "MSAMB",
    status: "Active",
    lastSyncAt: "2026-09-08T07:10:00Z",
  },
  {
    id: "MANDI-NSK-05",
    mandi: "Dindori APMC",
    marketCode: "MH-NSK-005",
    district: "Nashik",
    state: "Maharashtra",
    pincode: "422202",
    lat: 20.2,
    lng: 73.8333,
    supportedCrops: ["Tomato", "Grapes", "Vegetables"],
    dataSource: "MSAMB",
    status: "Active",
    lastSyncAt: "2026-09-08T07:20:00Z",
  },

  // Pune
  {
    id: "MANDI-PUN-01",
    mandi: "Pune Gultekdi Market Yard",
    marketCode: "MH-PUN-001",
    district: "Pune",
    state: "Maharashtra",
    pincode: "411037",
    lat: 18.4975,
    lng: 73.8643,
    supportedCrops: ["Tomato", "Onion", "Potato", "Pomegranate", "Banana", "Wheat"],
    dataSource: "Agmarknet (Govt of India)",
    status: "Active",
    lastSyncAt: "2026-09-08T08:00:00Z",
  },
  {
    id: "MANDI-PUN-02",
    mandi: "Baramati APMC",
    marketCode: "MH-PUN-002",
    district: "Pune",
    state: "Maharashtra",
    pincode: "413102",
    lat: 18.1517,
    lng: 74.5772,
    supportedCrops: ["Tomato", "Onion", "Soybean", "Pomegranate", "Wheat"],
    dataSource: "MSAMB",
    status: "Active",
    lastSyncAt: "2026-09-08T07:45:00Z",
  },
  {
    id: "MANDI-PUN-03",
    mandi: "Junnar APMC (Otur / Narayangaon)",
    marketCode: "MH-PUN-003",
    district: "Pune",
    state: "Maharashtra",
    pincode: "410504",
    lat: 19.2,
    lng: 73.88,
    supportedCrops: ["Tomato", "Onion", "Vegetables"],
    dataSource: "Agmarknet (Govt of India)",
    status: "Active",
    lastSyncAt: "2026-09-08T07:15:00Z",
  },
  {
    id: "MANDI-PUN-04",
    mandi: "Manchar APMC",
    marketCode: "MH-PUN-004",
    district: "Pune",
    state: "Maharashtra",
    pincode: "410503",
    lat: 19.0,
    lng: 73.9333,
    supportedCrops: ["Tomato", "Potato", "Onion"],
    dataSource: "MSAMB",
    status: "Active",
    lastSyncAt: "2026-09-08T06:50:00Z",
  },
  {
    id: "MANDI-PUN-05",
    mandi: "Khed Chakan APMC",
    marketCode: "MH-PUN-005",
    district: "Pune",
    state: "Maharashtra",
    pincode: "410501",
    lat: 18.76,
    lng: 73.85,
    supportedCrops: ["Onion", "Potato", "Vegetables"],
    dataSource: "Agmarknet (Govt of India)",
    status: "Active",
    lastSyncAt: "2026-09-08T07:05:00Z",
  },

  // Solapur
  {
    id: "MANDI-SOL-01",
    mandi: "Solapur APMC",
    marketCode: "MH-SOL-001",
    district: "Solapur",
    state: "Maharashtra",
    pincode: "413002",
    lat: 17.6599,
    lng: 75.9064,
    supportedCrops: ["Onion", "Pomegranate", "Turmeric", "Soybean", "Gram"],
    dataSource: "Agmarknet (Govt of India)",
    status: "Active",
    lastSyncAt: "2026-09-08T06:40:00Z",
  },
  {
    id: "MANDI-SOL-02",
    mandi: "Pandharpur APMC",
    marketCode: "MH-SOL-002",
    district: "Solapur",
    state: "Maharashtra",
    pincode: "413304",
    lat: 17.6775,
    lng: 75.3264,
    supportedCrops: ["Pomegranate", "Onion", "Maize"],
    dataSource: "MSAMB",
    status: "Active",
    lastSyncAt: "2026-09-08T07:00:00Z",
  },
  {
    id: "MANDI-SOL-03",
    mandi: "Sangola APMC",
    marketCode: "MH-SOL-003",
    district: "Solapur",
    state: "Maharashtra",
    pincode: "413307",
    lat: 17.4333,
    lng: 75.2,
    supportedCrops: ["Pomegranate", "Bajra"],
    dataSource: "Agmarknet (Govt of India)",
    status: "Active",
    lastSyncAt: "2026-09-08T06:20:00Z",
  },

  // Nagpur & Vidarbha
  {
    id: "MANDI-NGP-01",
    mandi: "Nagpur Cotton Yard & Kalamna APMC",
    marketCode: "MH-NGP-001",
    district: "Nagpur",
    state: "Maharashtra",
    pincode: "440008",
    lat: 21.1458,
    lng: 79.0882,
    supportedCrops: ["Cotton", "Soybean", "Orange", "Wheat", "Chilli"],
    dataSource: "Agmarknet (Govt of India)",
    status: "Active",
    lastSyncAt: "2026-09-08T08:15:00Z",
  },
  {
    id: "MANDI-NGP-02",
    mandi: "Katol APMC",
    marketCode: "MH-NGP-002",
    district: "Nagpur",
    state: "Maharashtra",
    pincode: "441302",
    lat: 21.2667,
    lng: 78.5833,
    supportedCrops: ["Orange", "Soybean", "Cotton"],
    dataSource: "MSAMB",
    status: "Active",
    lastSyncAt: "2026-09-08T06:50:00Z",
  },

  // Latur & Marathwada
  {
    id: "MANDI-LTR-01",
    mandi: "Latur Oilseed & Dal Market Yard",
    marketCode: "MH-LTR-001",
    district: "Latur",
    state: "Maharashtra",
    pincode: "413512",
    lat: 18.4088,
    lng: 76.5604,
    supportedCrops: ["Soybean", "Tur (Arhar)", "Gram", "Urad", "Moong"],
    dataSource: "Agmarknet (Govt of India)",
    status: "Active",
    lastSyncAt: "2026-09-08T07:25:00Z",
  },
  {
    id: "MANDI-LTR-02",
    mandi: "Ahmedpur APMC",
    marketCode: "MH-LTR-002",
    district: "Latur",
    state: "Maharashtra",
    pincode: "413515",
    lat: 18.7,
    lng: 76.9333,
    supportedCrops: ["Soybean", "Gram"],
    dataSource: "MSAMB",
    status: "Active",
    lastSyncAt: "2026-09-08T06:10:00Z",
  },

  // Other Major Maharashtra & National APMCs
  {
    id: "MANDI-MUM-01",
    mandi: "Mumbai Vashi APMC",
    marketCode: "MH-MUM-001",
    district: "Thane",
    state: "Maharashtra",
    pincode: "400703",
    lat: 19.076,
    lng: 72.998,
    supportedCrops: ["Tomato", "Onion", "Potato", "Grapes", "Pomegranate", "Banana"],
    dataSource: "Agmarknet (Govt of India)",
    status: "Active",
    lastSyncAt: "2026-09-08T08:30:00Z",
  },
  {
    id: "MANDI-SNG-01",
    mandi: "Sangli Spices & Turmeric Exchange",
    marketCode: "MH-SNG-001",
    district: "Sangli",
    state: "Maharashtra",
    pincode: "416416",
    lat: 16.8524,
    lng: 74.5815,
    supportedCrops: ["Turmeric", "Soybean", "Raisins", "Jaggery"],
    dataSource: "Agmarknet (Govt of India)",
    status: "Active",
    lastSyncAt: "2026-09-08T07:40:00Z",
  },
  {
    id: "MANDI-KOP-01",
    mandi: "Kolhapur APMC (Shahu Market Yard)",
    marketCode: "MH-KOP-001",
    district: "Kolhapur",
    state: "Maharashtra",
    pincode: "416005",
    lat: 16.705,
    lng: 74.2433,
    supportedCrops: ["Jaggery", "Tomato", "Soybean", "Ginger"],
    dataSource: "MSAMB",
    status: "Active",
    lastSyncAt: "2026-09-08T07:50:00Z",
  },
  {
    id: "MANDI-AUR-01",
    mandi: "Chhatrapati Sambhajinagar (Jadhavwadi) APMC",
    marketCode: "MH-AUR-001",
    district: "Chhatrapati Sambhajinagar",
    state: "Maharashtra",
    pincode: "431003",
    lat: 19.8762,
    lng: 75.3433,
    supportedCrops: ["Cotton", "Soybean", "Ginger", "Tomato"],
    dataSource: "e-NAM",
    status: "Active",
    lastSyncAt: "2026-09-08T06:55:00Z",
  },
  {
    id: "MANDI-DEL-01",
    mandi: "Delhi Azadpur Mandi",
    marketCode: "DL-DEL-001",
    district: "North Delhi",
    state: "Delhi",
    pincode: "110033",
    lat: 28.7126,
    lng: 77.1751,
    supportedCrops: ["Tomato", "Onion", "Potato", "Banana", "Apple", "Grapes"],
    dataSource: "Agmarknet (Govt of India)",
    status: "Active",
    lastSyncAt: "2026-09-08T08:00:00Z",
  },
  {
    id: "MANDI-BLR-01",
    mandi: "Bengaluru Yeshwanthpur APMC",
    marketCode: "KA-BLR-001",
    district: "Bengaluru Urban",
    state: "Karnataka",
    pincode: "560022",
    lat: 13.0285,
    lng: 77.5457,
    supportedCrops: ["Tomato", "Onion", "Potato", "Pomegranate", "Maize"],
    dataSource: "Agmarknet (Govt of India)",
    status: "Active",
    lastSyncAt: "2026-09-08T08:00:00Z",
  },
  {
    id: "MANDI-SUR-01",
    mandi: "Surat APMC",
    marketCode: "GJ-SUR-001",
    district: "Surat",
    state: "Gujarat",
    pincode: "395003",
    lat: 21.1702,
    lng: 72.8311,
    supportedCrops: ["Tomato", "Banana", "Cotton", "Vegetables"],
    dataSource: "e-NAM",
    status: "Active",
    lastSyncAt: "2026-09-08T07:15:00Z",
  },
];

export const initialCropsCatalog: CropCatalogItem[] = [
  {
    id: "CROP-TOM",
    name: "Tomato",
    marathiName: "टोमॅटो",
    hindiName: "टमाटर",
    category: "Vegetable",
    icon: "🍅",
    varieties: ["Abhinav (Hybrid)", "Vaibhav", "Saaho", "Rupali", "Local Desi"],
    perishability: "High (4-7 days)",
    storageRecommendation: "Ventilated crates at 12-15°C; avoid direct sun during transit.",
    defaultBatchSizeKg: 500,
    status: "Active",
    gradeRules: [
      { grade: "Grade A", minSizeMm: 55, maxDefectPct: 3, minColorScorePct: 90, priceAdjustmentPct: 10 },
      { grade: "Grade B", minSizeMm: 45, maxDefectPct: 8, minColorScorePct: 75, priceAdjustmentPct: 0 },
      { grade: "Grade C", minSizeMm: 35, maxDefectPct: 15, minColorScorePct: 60, priceAdjustmentPct: -15 },
    ],
  },
  {
    id: "CROP-ONI",
    name: "Onion",
    marathiName: "कांदा",
    hindiName: "प्याज़",
    category: "Vegetable",
    icon: "🧅",
    varieties: ["Unhali Red Garva", "Pol (Kharif Red)", "Rangada", "White Onion"],
    perishability: "Medium (1-3 weeks)",
    storageRecommendation: "Dry aerated chawl; moisture level < 65%.",
    defaultBatchSizeKg: 1000,
    status: "Active",
    gradeRules: [
      { grade: "Grade A", minSizeMm: 50, maxDefectPct: 2, priceAdjustmentPct: 12 },
      { grade: "Grade B", minSizeMm: 40, maxDefectPct: 6, priceAdjustmentPct: 0 },
      { grade: "Grade C", minSizeMm: 30, maxDefectPct: 12, priceAdjustmentPct: -18 },
    ],
  },
  {
    id: "CROP-SOY",
    name: "Soybean",
    marathiName: "सोयाबीन",
    hindiName: "सोयाबीन",
    category: "Grain",
    icon: "🌱",
    varieties: ["JS 335", "JS 9305", "MACS 1407", "Phule Kalyani (DS-228)"],
    perishability: "Low (Months)",
    storageRecommendation: "Grain godown with moisture <= 10%; fumigated pallets.",
    defaultBatchSizeKg: 2000,
    status: "Active",
    gradeRules: [
      { grade: "Grade A", maxDefectPct: 1.5, priceAdjustmentPct: 5 },
      { grade: "Grade B", maxDefectPct: 4.0, priceAdjustmentPct: 0 },
      { grade: "Grade C", maxDefectPct: 8.0, priceAdjustmentPct: -10 },
    ],
  },
  {
    id: "CROP-COT",
    name: "Cotton",
    marathiName: "कापूस",
    hindiName: "कपास",
    category: "Cash Crop",
    icon: "☁️",
    varieties: ["Bt Cotton Hybrid", "DCH-32", "Bunny Bt", "Ajeet 155"],
    perishability: "Low (Months)",
    storageRecommendation: "Covered dry bale shed; fire protection mandatory.",
    defaultBatchSizeKg: 2000,
    status: "Active",
    gradeRules: [
      { grade: "Grade A", maxDefectPct: 2, priceAdjustmentPct: 8 },
      { grade: "Grade B", maxDefectPct: 5, priceAdjustmentPct: 0 },
      { grade: "Grade C", maxDefectPct: 10, priceAdjustmentPct: -12 },
    ],
  },
  {
    id: "CROP-POM",
    name: "Pomegranate",
    marathiName: "डाळिंब",
    hindiName: "अनार",
    category: "Fruit",
    icon: "🍎",
    varieties: ["Bhagwa Export Grade", "Arakta", "Ganesh Super"],
    perishability: "Medium (1-3 weeks)",
    storageRecommendation: "Cold storage at 5-7°C; foam netting on individual fruits.",
    defaultBatchSizeKg: 800,
    status: "Active",
    gradeRules: [
      { grade: "Grade A", minSizeMm: 75, maxDefectPct: 1, minColorScorePct: 95, priceAdjustmentPct: 15 },
      { grade: "Grade B", minSizeMm: 65, maxDefectPct: 5, minColorScorePct: 80, priceAdjustmentPct: 0 },
      { grade: "Grade C", minSizeMm: 55, maxDefectPct: 12, minColorScorePct: 65, priceAdjustmentPct: -20 },
    ],
  },
  {
    id: "CROP-GRP",
    name: "Grapes",
    marathiName: "द्राक्षे",
    hindiName: "अंगूर",
    category: "Fruit",
    icon: "🍇",
    varieties: ["Thompson Seedless Export", "Sonaka", "Manik Chaman", "Sharad Seedless Black"],
    perishability: "Very High (1-3 days)",
    storageRecommendation: "Pre-cooled within 4 hours to 0-1°C with SO2 pads.",
    defaultBatchSizeKg: 1000,
    status: "Active",
    gradeRules: [
      { grade: "Grade A", minSizeMm: 18, maxDefectPct: 2, priceAdjustmentPct: 15 },
      { grade: "Grade B", minSizeMm: 15, maxDefectPct: 6, priceAdjustmentPct: 0 },
      { grade: "Grade C", minSizeMm: 12, maxDefectPct: 12, priceAdjustmentPct: -20 },
    ],
  },
  {
    id: "CROP-BAN",
    name: "Banana",
    marathiName: "केळी",
    hindiName: "केला",
    category: "Fruit",
    icon: "🍌",
    varieties: ["Grand Naine (G-9)", "Robusta", "Basrai", "Shrimanti"],
    perishability: "High (4-7 days)",
    storageRecommendation: "Controlled ripening chamber at 14-16°C.",
    defaultBatchSizeKg: 2500,
    status: "Active",
    gradeRules: [
      { grade: "Grade A", minSizeMm: 180, maxDefectPct: 3, priceAdjustmentPct: 10 },
      { grade: "Grade B", minSizeMm: 150, maxDefectPct: 8, priceAdjustmentPct: 0 },
      { grade: "Grade C", minSizeMm: 120, maxDefectPct: 15, priceAdjustmentPct: -15 },
    ],
  },
  {
    id: "CROP-WHE",
    name: "Wheat",
    marathiName: "गहू",
    hindiName: "गेहूं",
    category: "Grain",
    icon: "🌾",
    varieties: ["Lokwan 148", "Sharbati", "Kalyan Sona", "GW 496"],
    perishability: "Low (Months)",
    storageRecommendation: "Silo/godown storage at < 12% moisture.",
    defaultBatchSizeKg: 2000,
    status: "Active",
    gradeRules: [
      { grade: "Grade A", maxDefectPct: 1.0, priceAdjustmentPct: 5 },
      { grade: "Grade B", maxDefectPct: 3.5, priceAdjustmentPct: 0 },
      { grade: "Grade C", maxDefectPct: 7.0, priceAdjustmentPct: -8 },
    ],
  },
];

export const initialTransporters: Transporter[] = [
  {
    id: "TR-001",
    name: "Kisan Express Agro Logistics",
    contactPerson: "Santosh Kadam",
    phone: "9822398765",
    email: "dispatch@kisanexpress.in",
    baseLocation: "Baramati FPO Logistics Hub",
    baseLat: 18.1517,
    baseLng: 74.5772,
    serviceDistricts: ["Pune", "Solapur", "Satara", "Ahmednagar"],
    costPerKmInr: 2.2,
    vehicles: [
      {
        id: "VEH-01",
        regNumber: "MH-12-RN-5821",
        vehicleType: "Pickup Tempo",
        capacityKg: 1500,
        isRefrigerated: false,
        driverName: "Santosh Kadam",
        driverPhone: "9822398765",
        status: "Available",
      },
      {
        id: "VEH-02",
        regNumber: "MH-12-QT-3490",
        vehicleType: "Mini Truck (14ft)",
        capacityKg: 3500,
        isRefrigerated: false,
        driverName: "Baban Gaikwad",
        driverPhone: "9822398766",
        status: "Available",
      },
      {
        id: "VEH-03",
        regNumber: "MH-12-WX-8812",
        vehicleType: "Eicher 17ft",
        capacityKg: 7000,
        isRefrigerated: false,
        driverName: "Pandurang Patil",
        driverPhone: "9822398767",
        status: "In Transit",
      },
    ],
    status: "Active",
  },
  {
    id: "TR-002",
    name: "Sahyadri Cold Fleet Transport",
    contactPerson: "Vilas Thoke",
    phone: "9822045611",
    email: "coldchain@sahyadrifleet.com",
    baseLocation: "Mohadi Mega Packhouse, Nashik",
    baseLat: 20.006,
    baseLng: 73.882,
    serviceDistricts: ["Nashik", "Thane", "Mumbai", "Pune", "Jalgaon"],
    costPerKmInr: 2.8,
    vehicles: [
      {
        id: "VEH-04",
        regNumber: "MH-15-EM-7721",
        vehicleType: "Reefer Truck",
        capacityKg: 5000,
        isRefrigerated: true,
        driverName: "Sanjay Jagtap",
        driverPhone: "9822045612",
        status: "Available",
      },
      {
        id: "VEH-05",
        regNumber: "MH-15-GB-9901",
        vehicleType: "Reefer Truck",
        capacityKg: 9000,
        isRefrigerated: true,
        driverName: "Sachin Dhikale",
        driverPhone: "9822045613",
        status: "Available",
      },
    ],
    status: "Active",
  },
  {
    id: "TR-003",
    name: "Marathwada Kisan Freight Carriers",
    contactPerson: "Dnyaneshwar Munde",
    phone: "9422176540",
    email: "freight@marathwadakisan.org",
    baseLocation: "Parbhani & Latur Hubs",
    baseLat: 19.2608,
    baseLng: 76.7748,
    serviceDistricts: ["Parbhani", "Latur", "Nanded", "Hingoli", "Beed"],
    costPerKmInr: 2.0,
    vehicles: [
      {
        id: "VEH-06",
        regNumber: "MH-22-AA-4411",
        vehicleType: "Mini Truck (14ft)",
        capacityKg: 4000,
        isRefrigerated: false,
        driverName: "Sunil Waghmare",
        driverPhone: "9422176541",
        status: "Available",
      },
      {
        id: "VEH-07",
        regNumber: "MH-24-CC-8109",
        vehicleType: "Pickup Tempo",
        capacityKg: 1800,
        isRefrigerated: false,
        driverName: "Kishor Gore",
        driverPhone: "9422176542",
        status: "Available",
      },
    ],
    status: "Active",
  },
];

export const initialPlatformSettings: PlatformSettings = {
  defaultSearchRadiusKm: 100,
  minRadiusKm: 25,
  maxRadiusKm: 1000,
  radiusExpansionSteps: [25, 50, 100, 200, 300, 500, 1000],
  maxFarmerSelectableRadiusKm: 1000,
  allowFarmerCustomRadius: true,
  searchOnlyActiveMandis: true,
  searchOnlyWithLatestPrice: false,
  priceFreshnessThresholdHours: 24,
  stalePriceThresholdHours: 72,
  showMarketsWithoutLatestPrice: true,
  defaultCrop: "Tomato",
  defaultTransportCostPerKm: 2.2,
  defaultHandlingCostPaise: 15,
  defaultPackagingCostPaise: 35,
  defaultCommissionPct: 0,
  defaultExpectedSpoilagePct: 1.5,
  voiceAssistantModel: "gemini-2.5-flash",
  voiceAssistantSpeed: 1.0,
  enableLiveAgmarknetFeed: true,
};

export const initialRolePermissions: RolePermissions[] = [
  {
    role: "farmer",
    label: "Farmer (उत्पादक शेतकरी)",
    canViewMarketPrices: true,
    canUseVoiceAssistant: true,
    canGradeCrop: true,
    canCreatePools: false,
    canManageLogistics: false,
    canAuthorizeEscrow: false,
    canViewPrivateFarmerData: false,
    canManageUsers: false,
    canManageMandis: false,
    canManageSettings: false,
  },
  {
    role: "fpo",
    label: "FPO Manager (संस्था व्यवस्थापक)",
    canViewMarketPrices: true,
    canUseVoiceAssistant: true,
    canGradeCrop: true,
    canCreatePools: true,
    canManageLogistics: true,
    canAuthorizeEscrow: false,
    canViewPrivateFarmerData: true,
    canManageUsers: false,
    canManageMandis: false,
    canManageSettings: false,
  },
  {
    role: "buyer",
    label: "Institutional Buyer (थेट खरेदीदार)",
    canViewMarketPrices: true,
    canUseVoiceAssistant: true,
    canGradeCrop: false,
    canCreatePools: false,
    canManageLogistics: false,
    canAuthorizeEscrow: false,
    canViewPrivateFarmerData: false,
    canManageUsers: false,
    canManageMandis: false,
    canManageSettings: false,
  },
  {
    role: "admin",
    label: "Platform Admin (मुख्य प्रशासक)",
    canViewMarketPrices: true,
    canUseVoiceAssistant: true,
    canGradeCrop: true,
    canCreatePools: true,
    canManageLogistics: true,
    canAuthorizeEscrow: true,
    canViewPrivateFarmerData: true,
    canManageUsers: true,
    canManageMandis: true,
    canManageSettings: true,
  },
];
